#! /bin/sh

sxhkd &
xbindkeys &
feh --bg-scale "/home/labibmahmud/.config/backgrounds/city.jpg" &
# feh --bg-max "/home/labibmahmud/.config/backgrounds/anime.jpg" &
$HOME/.config/polybar/launch.sh &
compton -f &
exec /usr/lib/x86_64-linux-gnu/xfce4/notifyd/xfce4-notifyd &

# Sets dual monitors, change HDMI1 to your according output
# xrandr --output eDP1 --auto --output HDMI1 --left-of eDP1 &

# Set second monitor as primary monitor, change HDMI1 to your according output
# xrandr --output eDP1 --off --output HDMI1 --auto &

# Regular monitor output
bspc monitor -d I II III IV V VI VII VIII IX X

# To split the number of workspaces between the two displays, uncomment the two lines below.
# bspc monitor HDMI1 -d  I II III IV V  
# bspc monitor eDP1 -d VI VII VIII IX X

# When setting HDMI display as primary display, uncomment the line below.
# bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X

### WINDOW CONFIG ###
bspc config border_width         1
bspc config top_padding         20
# bspc config bottom_padding      30
bspc config window_gap           5
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color  \#0c0d12
bspc config active_border_color \#ffffff

### APPLICATION RULES ###
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Lightworks state=fullscreen
