#! /bin/sh

sxhkd &
feh --bg-scale "/home/labibmahmud/.pictures/background.jpg" &
xfce4-panel &
exec /usr/lib/x86_64-linux-gnu/xfce4/notifyd/xfce4-notifyd &
compton -f &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config top_padding         30
bspc config bottom_padding      30
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
